### ISSUE TITLE
Redox and Redox_w keyboards not working on GUI

### ISSUE THREAD

**Issue by Pastitas** [vial-kb/vial-gui#142]
Currently on the GUI there's no support for redox or redox_w because of a problem in the via json files. In the first entry of the layout there's a ``` "a": 7 ```
line that needs to be removed  for the sideloading to work. 
Can this be fixed or the fix needs to come from upstream?

Also matrix testing and other features seem to be missing but this might be related with the sideloading process so I don't know if it's also a bug

Thanks for the awesome work btw, vial is working better than via for me!!

**Comment by xyzz** [comment]
It would have to be fixed on the VIA side.

**Comment by xyzz** [comment]
A firmware compiled for Vial (i.e. with VIAL_ENABLE) would not use VIA definitions, these are only used in a limited backwards-compatibility mode for VIA keyboards.

**Comment by Pastitas** [comment]
Well then there's a bug because I'm using the vial firmware that I compiled with the settings that were in the PR and the gui still needs sideloading of the corrected json from vial. 
Do you mean that we're lacking the json in the vial repos for my specific keyboards? If so, where should they go? I can make a PR

**Comment by rufusw** [comment]
I added Redox support back in May (which included fixing the layout bug you mentioned) and have been using my Redox with Vial ever since then. 
For Redox_w you have the vial.json in the right place but you haven't fixed the layout bug.
https://github.com/vial-kb/vial-qmk/blob/vial/keyboards/redox_w/keymaps/vial/vial.json line 9. If you fix that hopefully it will work.
