### ISSUE TITLE
Will TL_LOWR and TL_UPPR be added?

### ISSUE THREAD

**Issue by doesntfazer** [vial-kb/vial-gui#172]
It looks like the way that Tri-Layer-State is handled has changed. I was wondering when/if this feature will be available now that it's as simple as adding `TRI_LAYER_ENABLE = yes` to the `rules.mk`

https://docs.qmk.fm/#/feature_tri_layer?id=tri-layers

Looks like there's a couple more things you can do like define which layers are tri-layer in the `config.h.`

**Comment by xyzz** [comment]
The feature has been available in vial since the release under these two buttons:
![image](https://user-images.githubusercontent.com/1065521/231344946-5d5692eb-a84a-41b3-b189-dac1e5c8599a.png)
if the question is whether it's gonna switch to the new tri-state layer implementation then the answer is yes

**Comment by doesntfazer** [comment]
Thank you for the heads up! I was actually unaware of this.
