### ISSUE TITLE
Add System76 Launch

### ISSUE THREAD

**Issue by ahoneybun** [vial-kb/vial-gui#49]
This application doesn't support the Launch by System76. I ran though the steps for udev but it still doesn't detect it. 

Some information about this keyboard:

lsusb:

Bus 001 Device 006: ID 3384:0001 System76 Launch Configurable Keyboard (launch_1)
Bus 001 Device 006: ID 3384:0001 System76 Launch Configurable Keyboard (launch_1)

**Comment by xyzz** [comment]
The vial team does not implement support for any specific keyboard - the keyboard maker will have to follow instructions in Vial porting guide (https://get.vial.today/docs/) in order to create a version of the qmk firmware which has vial support. After that firmware is flashed to the keyboard, it will be automatically detected by the GUI. To confirm whether a specific board is running Vial-enabled firmware, you can run `usb-devices` and look for `SerialNumber=vial:f64c2b3c`.
